### PR TITLE
Feature/ValidateRegistriesName

### PR DESCRIPTION
**Pull request by Vreyesm**
#### Important:
- [Last commit](https://github.com/Taller-2018-1/core/commit/62aec93ce702d94d12999e9209ae0154aa40ab51) fixes a big issue introduced on the [first commit](https://github.com/Taller-2018-1/core/commit/d5045e39462a7d0383f15e925a39a172d2373ec3).
Basically, I had to redo all the changes from that commit on the api and change some things on angular side.
- `npm install` needed, SweetAlert2 dependency added.

#### Added:
- Api end-point to verify if already exists a registry with the specified name.
- Angular service to obtain the boolean value from the api.
- Angular verification when the user tries to add a registry (and notification).
- Notification (alert) uses SweetAlert2 (new dependency).

##### Note:
- I will refactor some alerts to use SweetAlert2 instead of `alert()`.
Probably it will be added on this pr, if I have enough time. If not, I will create a new branch.
##### Update:
- Confirmation messages when the user tries to delete a document or a registry are now showing using SweetAler2.
- Alert message when a document can't be deleted (there is only one document) are now showing using SweetAlert2.
- Extra: Navigation buttons position swapped.

### CODE REVIEW

**Comment by Vreyesm** [comment]
[Validar nombres de los registros al agregar un nuevo registro.](https://trello.com/c/Bmdb0x2G/51-validar-nombres-de-los-registros-al-agregar-un-nuevo-registro)

**Comment by Vreyesm** [comment]
Bug detected, closed.

**Comment by Vreyesm** [comment]
Bug fixed

**Comment by Alisboa13** [comment]
Additional work is recommended. See #70

**Pull request merged**
